name: Testing workflow

on: [push]

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Install clang style checker"
        run: sudo apt install clang-format
      - name: "Check style in src directory"
        run: clang-format --dry-run -Werror src/*
      - name: "Check style in tests directory"
        run: clang-format --dry-run -Werror tests/*.cpp
  build:
    needs: style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Install dependencies"
        run: sudo apt install cmake libeigen3-dev libyaml-cpp-dev libboost-all-dev
      - name: "Create build directory"
        run: mkdir build 
      - name: "Configure CMake and execute make" 
        run: cd build && cmake .. && make -j
      - name: "Zip upload file"
        run: tar -cvf build.tar build
      - name: "Artifact upload"
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build.tar
          retention-days: 14
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Install dependencies"
        run: sudo apt install cmake libeigen3-dev libyaml-cpp-dev libboost-test-dev
      - name: "Download artifact"
        uses: actions/download-artifact@v2
        with:
          name: build
      - name: "Unzip artifact"
        run: tar -xf build.tar
      - name: "Run tests in build directory" 
        run: cd build && make test
